baseURL='https://kpstyatw.github.io/'
locale = 'zh-cn'
title='我的博客'

theme='PaperMod'
[menu]

[[menu.main]]
identifier="home"
name="Home"
url="/"
weight=10

[[menu.main]]
identifier="ai"
name="AI"
url="/tags/AI/"
weight=20

[[menu.main]]
identifier="ivd"
name="IVD"
url="/tags/IVD/"
weight=30

[[menu.main]]
identifier="python"
name="Python"
url="/tags/Python/"
weight=40

[[menu.main]]
identifier="projects"
name="Projects"
url="/projects/"
weight=50

[[menu.main]]
identifier="about"
name="About"
url="/about/"
weight=60

[outputs]

home = ["HTML","RSS","JSON"]
params.search=true

[params.math]

enable=true